DROP TABLE IF EXISTS realty;

CREATE TABLE realty (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  square INTEGER NOT NULL,
  bathrooms INTEGER DEFAULT NULL,
  bedrooms INTEGER DEFAULT NULL,
  water_supply INTEGER DEFAULT NULL,
  electricity INTEGER DEFAULT NULL,
  straits INTEGER DEFAULT NULL,
  kitchen INTEGER DEFAULT NULL
);
